version: '3.7'

services:
  db:
    image: postgres
    restart: always
    healthcheck:
      test: "pg_isready -q -U postgres"
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: example
  
  migrations:
    image: boxfuse/flyway
    command: -url=jdbc:postgresql://db/example -schemas=public -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db